import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useMutation, useQueryClient } from 'react-query'
import useAuth from '../hooks/useAuth'
import { Api } from '../services/api'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const {
    authData,
    isLogged,
    isLogging,
  } = useAuth()
  const queryClient = useQueryClient();
  const { mutate: getSomething } = useMutation(Api.getSomething, {
    onSuccess: (data) => {
      console.log('test: ', data)
      queryClient.setQueryData('test', data);
    }
  })
  console.log('authData: ', authData)
  return (
    <div className={styles.container}>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          {
            isLogging 
            ? <p>Loading...</p>
            : <>
                Welcome to <a href="https://nextjs.org">Next.js!</a>
                <button onClick={(e) => {
                  e.preventDefault()
                  getSomething(authData!.code)
                }}>get something</button>
              </>
          }
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
